apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-app
  ports:
  - port: 8082
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
spec:
  selector:
    matchLabels:
      app: product-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: diegochavezcarro/product-app:1.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 400Mi
            cpu: 400m
        ports:
        - containerPort: 8082
